#!/bin/sh
## smartcard/setup_smartcard
## THIS FILE IS UNDER CVS CONTROL AND DISTRIBUTED BY SUP
## $Id$

# make sure we're in a reasonable state
pkill ocfserv
opensc-tool -l
opensc-tool -nw

echo "Enter username: \c"
read username
echo "Enter user's full name: \c"
read fullname

echo ""
echo "Initializing card..."
pkcs15-init -TEC -l "$username" --no-so-pin -c /usr/tmp/flex.profile

echo ""
echo "Establishing PIN..."
pkcs15-init -TP -a 01 -l "MiniWorld Access" --puk ''
echo "You will need to type the PIN several more times to complete card setup"

echo ""
echo "Generating login key..."
pkcs15-init -G rsa/1024 -a 01 -i 55 -l "MW Login"
openssl req -engine /usr/local/lib/opensc/engine_opensc.so \
  -new -x509 -key 55 -keyform engine -out /tmp/$username.login.crt \
  -subj "/C=US/ST=Pennsylvania/L=Pittsburgh/O=Carnegie Mellon University/OU=School of Computer Science/OU=Facilities/CN=$fullname - Login/emailAddress=$username@cs.cmu.edu/"
pkcs15-init -X /tmp/$username.login.crt -i 55 -l "MW Login"

echo ""
echo "Generating kdb access key..."
pkcs15-init -G rsa/1024 -a 01 -i 56 -l "KDB Access" -u decrypt
pkcs15-tool --read-public-key 56 -o /tmp/$username.kdb.key

echo ""
echo "Card setup is complete"
echo "Login cert is in /tmp/$username.login.crt"
echo "KDB public key is in /tmp/$username.kdb.key"
